apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kleva-ingress
  namespace: kleva
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  ingressClassName: nginx
  rules:
    - host: app.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kleva-frontend
                port:
                  number: 80
    - host: voice.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kleva-backend
                port:
                  number: 8000
